appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {osx: circle}
shippable:
  projectId: 5c3421f9c05bae0700d40f42
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: l8+QXBIy9wcXpHWT1hjQn4lyPH3/4i48Zy7PUcrtcwBDsr8h9tfMxMLxaqjjggCtk7oHK79NVEH0GOxW8Rh8JM++I7iHZEgTLlW2Rk9V9J0ViG1miK921/YOsl2oN5a8Hg/0fHzo9Heh67iD7GvcSHV0aMHNWrbI+NCgaMV9MO7OKMzHQBjMvfdl8u8yvUHezWLXEvn3kSW1OJmUJ66LmdNNvpJopOatiNy4rFU2C2p6PTeF8j48MWp2/OWs5dBu8WQRR4iEUZRmWYNJ3ldb73z9UROAOAyUN6fYaBK5bTSxGz5Pyn2NMSdbVhHJpf7BJfxpuevG2IlC4UtJF/htGNVMcrCYDT6b6b1D7JptuhX8/6+FMh2T4/j24msIE/HEydH9EQIDAMDcvuLp67fnv1wwMNIBYqiXqMIApuanqQZdvWrw+/NI9RUM0OmoMTqcwYm0PnVIY3nI07L0eempu5fHLSJBD7HfxbEBSDUMlPL/9Xl4ZnOnqYak857OnFWMNu7o83Bq6gQ8k97kD7F5ofFRUgI23qxubF4Bygse2sltdJSqztFElIVodZgrtmgK+u9HdZ5nP+A6DtS+nDr8yvB6NH+QHrCJgrQ/tkK/XopLxS/sqiERZtj70IifWBV/M+df67LPw7NKLpvddbAYI82cuWIkMSrwoZ9CRfYiuwE=}
